# Generic task to install mapp software

---
- name: INSTALL setup-files
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  tasks:        

    - name: Install Python-apt
      raw: dpkg -l | grep python-apt || apt-get install python-apt

  tasks:
    - name: Creating directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/etc/tseries"
        - "/usr/share/tseries/style"
        - "/usr/share/pixmaps/tseries"
        - "/usr/share/applications"
      tags: dir
    
    - name: Copy Tseries etc files
      copy:
        src: "{{ item }}"
        dest: "/etc/tseries/"
      with_fileglob:
        - "files/etc/*"
      tags: etc
      
    - name: Copy Tseries style files
      copy:
        src: "{{ item }}"
        dest: "/usr/share/tseries/style/"
      with_fileglob:
        - "files/style/*"
      tags: style
        
    - name: Copy Tseries Pixmaps
      copy:
        src: "{{ item }}"
        dest: "/usr/share/pixmaps/tseries/"
      with_fileglob:
        - "files/pixmaps/*"
      tags: pixmaps

    - name: Copy Tseries Logo
      copy:
        src: "files/pixmaps/tseries.png"
        dest: "/usr/share/pixmaps/"












        
